name: CI

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Fetch main branch
        run: git fetch origin main:main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Disable Husky in CI
        run: git config core.hooksPath /dev/null

      - name: Check formatting
        run: npx nx format:check --all

      - name: Lint affected projects (do not fail on error)
        run: |
          npx nx affected:lint --base=main --max-warnings=9999 || \
          npx nx affected:lint --all --max-warnings=9999 || true

      - name: Run affected tests
        run: |
          npx nx affected:test --base=main --ci --code-coverage || \
          npx nx affected:test --all --ci --code-coverage || true

      # - name: Build affected projects
      #   run: |
      #     npx nx affected:build --base=main || \
      #     npx nx affected:build --all
