name: CI

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Disable Husky in CI
        run: git config core.hooksPath /dev/null

      - name: Check formatting
        run: npx nx format:check

      - name: Lint affected projects
        run: npx nx affected:lint --base=origin/main

      - name: Run affected tests
        run: npx nx affected:test --base=origin/main --ci --code-coverage

      - name: Build affected projects
        run: npx nx affected:build --base=origin/main
